### ISSUE TITLE
Clientconfig and babel

### ISSUE THREAD

**Issue by funkyduke** [modmore/ClientConfig#140] opened 2018-01-25 15:00 UTC
When following documentation about Babel there's a suggestion to make a gateway-plugin with a System event OnHandleRequest. (http://www.multilingual-modx.com/blog/2011/seo-friendly-multilingual-websites-with-modx-and-babel.html)

But when you work with clientconfig (version 2) then it's better to choose OnModxInit and give it a priority lower than clientconfig.

**Comment by OptimusCrime** [comment] 2018-02-21 10:54
I do not understand this issue. Is this a question? Modmore has nothing to do with the website you linked to.

**Comment by Mark-H** [comment] 2018-02-21 11:14
I asked @funkyduke to report this in case there is something we can do about it. The issue is that clientconfig's new context-aware settings don't work with the recommended babel gateway plugin because of the difference in when they are fired. Switching OnHandleRequest o OnMODXInit in the Babel gateway plugin fixes that.

Was hoping the recommended plugin code was in the RTFM or somewhere though, not sure how to go about getting that particular site updated... no idea who runs that.

**Comment by joyceDesignbase** [comment] 2018-03-14 20:19
For me this fix does not work? It looks like it 'sees' the correct amount of contexts but doesn't find the data. I set priority of clientconfig OnMODXInit event to 1 and  on gateway plugin switched OnHandleRequest to OnMODXInit and set priority to 0.

Modx 2.6.1

Any suggestions? This is a very cool feature I would love to use on my site with 4 languages!

![screen shot 2018-03-14 at 21 13 52](https://user-images.githubusercontent.com/2427268/37428576-f95166d4-27cc-11e8-9472-942be3cbec23.png)

**Comment by Mark-H** [comment] 2018-03-14 20:21
@joyceDesignbase That does not look like the same issue reported here. I think you just need to make sure each of your contexts have a name set (and not just a key). If they do all have a name, please open a separate issue.

**Comment by joyceDesignbase** [comment] 2018-03-14 20:30
Thank you, that was it! Sorry I didn't know that you had to set a name.

**Comment by Mark-H** [comment] 2019-10-24 12:41
I've slightly changed this in 2.3; it will now automatically run on both OnHandleRequest _and_ OnMODXInit events. A little wasteful, because it really only should have to use one, but then I can finally close this and related issues. ;)

**Closed by Mark-H** 2019-10-24 12:41 UTC
